### ISSUE TITLE
Password strength validation

### ISSUE THREAD

**Issue by nixpulvis** [nuacm/website#17]
Passwords should be validated to fit the following.
- 6 characters long

**Comment by nixpulvis** [comment]
@ali Do we care too much about this?

**Comment by joshcaron** [comment]
I'm going to jump in on this and say yes, and that we shouldn't care about this at all. These passwords should just be throwaways that don't really matter seeing as we all have access to the database where they are stored.

**Comment by nixpulvis** [comment]
Um... I want to allow officers to log into the site and edit things. Interacting with the database directly will be really messy, so with that in mind the password with the officer account will be the primary method of interacting with the site as an officer (I don't want people touching the backend unnecessarily). Also, at some point (soon) we want members to be able to post photos and links so we need to let them have a password. The password is important I just want to ensure the validations scheme is not silly.

**Comment by ali** [comment]
@nixpulvis Not a priority, but if you want to validate length go for it.
