### ISSUE TITLE
Name Capitalization Fixing

### ISSUE THREAD

**Issue by nixpulvis** [nuacm/website#53]
Here's the issue...

![screen shot 2013-10-16 at 1 57 44 am](https://f.cloud.github.com/assets/715947/1340279/ed9583f2-3627-11e3-9b2d-b5fb2ddfdcb3.png)

**Comment by ali** [comment]
No that's how you spell her name.

**Comment by nixpulvis** [comment]
She informed me that her name was simply too awesome to be constrained to lowercase letters.

**Comment by ali** [comment]
https://www.youtube.com/watch?v=ewc1hixzYPY

**Comment by nixpulvis** [comment]
I approve.
