### ISSUE TITLE
Error Pages

### ISSUE THREAD

**Issue by nixpulvis** [nuacm/website#56]
This is the `public/404.html`, `public/422.html`, `public/500.html`. Currently they are the rails defaults, and this is bad.

**Comment by nixpulvis** [comment]
@joshcaron @aliceyoung9 You guys want to make these?

**Comment by aceyoung9** [comment]
K. Where do these go?

Alice Young

**Comment by nixpulvis** [comment]
I put the path's to all 3 in the description. You should just edit these static files.
