### ISSUE TITLE
Give the Officers page some love

### ISSUE THREAD

**Issue by ali** [nuacm/website#77]
The officer page currently lists users who are officers. That list is incomplete until every officer has signed up for an account.

We also got an email from the advising office because they wanted a list of current officers, and I couldn't just give them a link to the officers page. Womp womp.
## What it should have (at the minimum):
- Team photo
- Photo next to each officer's name (Gravatar style?)
- Title for each officer

**Comment by nixpulvis** [comment]
Do we want to use Gravatar? I'm all for it by adding a private gravatar email to the member model. I think it's probably the best option.

Do we have a team photo. I don't remember ever taking one. If we need to take one lets plan that out.

**Comment by ali** [comment]
How about we just use the Gravatar for whatever email they signed up with? Gravatar already has support for multiple emails, so we don't have to support it.

We don't have a team photo (yet). @joshcaron @zack Either of you want to make that happen?

**Comment by zack** [comment]
Making it happen would be as easy as getting everyone together in one place at one time for a minimum of three minutes.

So... not that easy. But we could throw up a doodle and then shop in anyone who doesn't show up. (:

**Comment by nixpulvis** [comment]
I was just thinking of email security, I didn't realize gravatar images hash out the original email. So I'm fine using the sign up email.

As far as a group photo is concerned, I'll make a poll hopefully we can get this. If not I'd say it's an opportunity to make creative use of photoshop :wink:

**Comment by ali** [comment]
Team photo is a wishlist item. We can make that a thing early next semester or something, so don't focus on it.

I guess all we need are Gravatars and titles.

**Comment by nixpulvis** [comment]
Ok I'll get this done.
